# Generated by Django 5.1.6 on 2025-04-17 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Documents administratifs', 'Documents administratifs'), ('Documents financiers', 'Documents financiers'), ('Documents techniques', 'Documents techniques'), ('Documents relatifs à la gestion des travaux', 'Documents relatifs à la gestion des travaux'), ('Documents relatifs aux assurances', 'Documents relatifs aux assurances'), ('Documents juridiques', 'Documents juridiques')], max_length=100),
        ),
    ]
