# Generated by Django 5.1.6 on 2025-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0002_document_date_creation_alter_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='part_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
