# Generated by Django 5.1.6 on 2025-04-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0003_document_part_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='part_percentage',
        ),
    ]
