# Generated by Django 5.1.6 on 2025-04-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0005_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='visibility',
        ),
    ]
