# Generated by Django 5.1.6 on 2025-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0006_remove_invoice_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Documents administratifs', 'Documents administratifs'), ('Documents financiers', 'Documents financiers'), ('Documents techniques', 'Documents techniques'), ('Documents relatifs à la gestion des travaux', 'Documents relatifs à la gestion des travaux'), ('Documents relatifs aux assurances', 'Documents relatifs aux assurances'), ('Documents juridiques', 'Documents juridiques'), ('Factures', 'Factures')], max_length=100),
        ),
    ]
