# Generated by Django 5.1.7 on 2025-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0008_document_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
