# Generated by Django 5.1.6 on 2025-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_customuser_phone_customuser_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=5255, max_length=30),
            preserve_default=False,
        ),
    ]
