# Generated by Django 5.1.6 on 2025-04-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties_app', '0004_alter_property_part_percentage'),
        ('residences_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='residences_app.residence')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.FloatField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='charges_app.charge')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='properties_app.property')),
            ],
        ),
    ]
