# Generated by Django 5.1.6 on 2025-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.CharField(choices=[('charges_generales', 'Charges Générales'), ('ascenseur', 'Ascenseur'), ('jardin', 'Jardin')], max_length=50),
        ),
    ]
