# Generated by Django 5.1.6 on 2025-04-22 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_app', '0002_alter_charge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
