# Generated by Django 5.1.6 on 2025-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_app', '0003_charge_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.CharField(choices=[('charges_generales', 'Charges Générales'), ('ascenseur', 'Ascenseur'), ('jardin', 'Jardin'), ('testing', 'testing')], max_length=50),
        ),
    ]
