# Generated by Django 5.1.7 on 2025-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_app', '0005_alter_charge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.CharField(choices=[('charges_generales', 'Charges Générales'), ('ascenseur', 'Ascenseur'), ('jardin', 'Jardin'), ('testing', 'testing')], max_length=50),
        ),
    ]
