# Generated by Django 5.1.7 on 2025-05-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_app', '0006_alter_charge_category'),
        ('residences_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.CharField(choices=[('charges_generales', 'Charges Générales'), ('ascenseur', 'Ascenseur'), ('testing', 'testing'), ('plomberie', 'Plomberie'), ('électricité', 'Électricité'), ('jardinage', 'Jardinage'), ('nettoyage', 'Nettoyage')], max_length=50),
        ),
        migrations.CreateModel(
            name='ChargePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('predicted_price', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences_app.residence')),
            ],
            options={
                'unique_together': {('residence', 'category', 'year', 'month')},
            },
        ),
    ]
