# Generated by Django 5.1.7 on 2025-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges_app', '0008_alter_charge_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
