# Generated by Django 5.1.6 on 2025-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0003_alter_property_part_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='part_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
