# Generated by Django 5.1.6 on 2025-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0004_alter_property_part_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='part_percentage',
        ),
        migrations.AddField(
            model_name='property',
            name='category_shares',
            field=models.JSONField(null=True),
        ),
    ]
